### ISSUE TITLE
The activities API does not return private activities

### ISSUE THREAD

**Issue by beverloo** [AnimeNL/rest-api#38]
Private events (i.e. those with `visible: false`) are not being returned when calling the `activities.json` API. Those same activities will be returned when calling the `timeslots.json` API however.

Is it possible that the [`ActivityDataProvider`](https://github.com/AnimeNL/rest-api/blob/master/src/DataProvider/Anplan/ActivityDataProvider.php) filters them out, whereas a [`Timeslot`](https://github.com/AnimeNL/rest-api/blob/master/src/Entity/Anplan/Timeslot.php) seems to be a simpler entity type? The check in `ActivityDataProvider::isAllowedToViewHidden()` verifies whether `ROLE_STAFF` is granted, I'm not sure how to tell whether my account has got that.

**Comment by janvernieuwe** [comment]
I'm guessing the annotation here https://github.com/AnimeNL/rest-api/blob/da8c0b8b0396d4c675b5e18437f95d9980db6c2c/src/Entity/Anplan/Activity.php#L31 is incorrect and should be a BooleanFilter like with Timeslot

**Comment by beverloo** [comment]
This now works. Thanks!
