### ISSUE TITLE
Expose the festival ID in the activities API

### ISSUE THREAD

**Issue by beverloo** [AnimeNL/rest-api#39]
Could the `pac_festival_id` field be included in the `activities.json` API response please? Fine for it to be gated on access.

We currently expose the `year` field, however, in practice that is a mess. For 2023 the values `2023`, `20236`, `202306` and `202309` were used (for unknown reason).

I see that other users, e.g. the [event viewer](https://github.com/AnimeNL/event-viewer/blob/master/src/libs/anime.js#L93), rely on the `timeslots.json` API with a date filter instead, most likely to work around this issue. I'd like to avoid that because that API follows a very different structure, and is rather wasteful in its response.

Happy to send a (naive) PR if that helps, but I have no idea how to test it, and can't deploy it.

**Comment by janvernieuwe** [comment]
I'll look into adding some more test that are between unit and functional to check for serialization issues. The deployment happens automatically after merging to main if all is well.
