### ISSUE TITLE
Figure out how to include floor information

### ISSUE THREAD

**Issue by beverloo** [AnimeNL/rest-api#45]
Currently, information about locations is included in the [Activities API](https://github.com/AnimeNL/rest-api/blob/master/src/Entity/Anplan/Activity.php) response, which looks like this:

```json
{
    "lots of field omitted for conciseness": true,
    "timeslots": [
        {
            "id": 103653,
            "dateStartsAt": "2023-06-09T14:00:00+00:00",
            "dateEndsAt": "2023-06-09T22:00:00+00:00",
            "location": {
                "id": 5337,
                "year": 20219,
                "name": "Exp Plaza",
                "useName": null,
                "sponsor": null
            }
        }
    ]
}
```

Information about which floor a location on is missing, even though someone [clearly has considered including it](https://github.com/AnimeNL/rest-api/blob/master/src/Entity/Anplan/Location.php#L63). The field is not populated in any of the responses, so that's definitely broken.

Then, separately, we have the [Floor API](https://github.com/AnimeNL/rest-api/blob/master/src/Entity/Anplan/Floor.php). That's a rather pointless endpoint since it gives a list of _every floor_ for _every event known in AnPlan_ without any information beyond the floor's name.

```json
[
    { "lots of entries omitted for conciseness": true },
    {
        "name": "Entrance area"
    },
    {
        "name": "Bakkerij 1"
    },
    {
        "name": "Bakkerij 2"
    },
    {
        "name": "Terrace"
    },
    {
        "name": "Entrance area"
    },
    {
        "name": "Bakkerij 1"
    },
    {
        "name": "Bakkerij 2"
    },
    {
        "name": "Terrace"
    }
]
```

My goal is that I'd like to be able **to group locations by the floor (or area) they're located on**.

The simplest way to achieve this would be for the `Location` type to include the floor's ID and name. The more comprehensive way to achieve this would be for the `Location` type to include the full `Floor` type as the code intended to happen, including the floor's description—which is cleaner but would result in many more bytes in the response.

Thoughts? Does anyone remember the intention of the code through which `Floor` _might_ be included in the `Location` type?

**Comment by janvernieuwe** [comment]
Hey @beverloo,

Ben even aan het kijken, en die floor id steekt bij de locations. 
Ik ga eens kijken om die te exposen, en dat samen met die activity fix live te zetten.

**Comment by beverloo** [comment]
This is now live :)
