### ISSUE TITLE
Timezone v3?

### ISSUE THREAD

**Issue by beverloo** [AnimeNL/rest-api#51]
After 9ba61b1 and a366a9f timezones were working well, but something seems to have changed early February that created new strange behaviour...

Take activity 42638 ("Bag Room & Lockers"), for which following timeslots are returned by the API:
```json
[
    {"id":103960,"dateStartsAt":"2024-06-07T16:00:00+02:00","dateEndsAt":"2024-06-08T04:00:00+02:00","location":{"id":5360,"year":20249,"name":"Bag room","useName":null,"sponsor":null,"area":"Bakkerij 1","floorId":379}}
    {"id":103962,"dateStartsAt":"2024-06-09T12:00:00+02:00","dateEndsAt":"2024-06-09T22:00:00+02:00","location":{"id":5360,"year":20249,"name":"Bag room","useName":null,"sponsor":null,"area":"Bakkerij 1","floorId":379}}
    {"id":103964,"dateStartsAt":"2024-06-08T12:00:00+02:00","dateEndsAt":"2024-06-09T04:00:00+02:00","location":{"id":5360,"year":20249,"name":"Bag room","useName":null,"sponsor":null,"area":"Bakkerij 1","floorId":379}}
]
```

It suggests that the first timeslot (103960) starts on `2024-06-07T16:00:00+02:00` while it actually starts on `2024-06-07T14:00:00+02:00`—two hours earlier.

If I run the code from a366a9f locally with `$input` set to the correct UNIX timestamp of the timeslot starting time in UTC, it outputs `2024-06-07T14:00:00+02:00` as expected.

```php
<?php
$input = 1717761600;

$local = new DateTimeZone('Europe/Amsterdam');
$timezonedDate = DateTime::createFromFormat('U', (string) $input, $local);
if ($timezonedDate === false) {
    throw new \Exception('Could not create DateTime from timestamp');
}

echo $timezonedDate->setTimezone($local)->format(DATE_ATOM);
```

It looks like something may have caused the input changed timezone?

**Comment by janvernieuwe** [comment]
Is this for all or only some events? 
Very strange we didnt change anything. Perhaps something on the server or database changed?
